version: '3'
services:
  wp:
    build: .
    ports:
      - "8000:80"
    environment:
      - WORDPRESS_DB_PASSWORD=qwerty
      - WORDPRESS_DEBUG=1
    volumes:
      - ./dist:/var/www/html/wp-content/themes/min
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:


